services:
  db:
    container_name: cronus-db
    image: postgres:14.0-alpine
    command:
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cronet
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports: 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: cronus-app
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./migrations:/usr/src/app/migrations
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    ports:
      - 5001:5000
    networks:
      - cronet