version: '3.4'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    ports:
      - 5001:5000
