"""Initial migration.

Revision ID: 3b0feed81a52
Revises: 
Create Date: 2022-02-08 16:49:10.968038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0feed81a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biopsy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('tumor_normal', sa.String(), nullable=True),
    sa.Column('sample_storage_method', sa.String(), nullable=True),
    sa.Column('tumor_content', sa.Float(), nullable=True),
    sa.Column('ploidy', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('t_stage', sa.String(), nullable=True),
    sa.Column('n_stage', sa.String(), nullable=True),
    sa.Column('m_stage', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('diagnosis_detailed', sa.String(), nullable=True),
    sa.Column('dense_subtype', sa.String(), nullable=True),
    sa.Column('MSI', sa.String(), nullable=True),
    sa.Column('tumor_mutational_burden', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('biopsy_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['biopsy_id'], ['biopsy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_case',
    sa.Column('sequence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('sequence_id', 'case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_case')
    op.drop_table('sequence')
    op.drop_table('case')
    op.drop_table('biopsy')
    op.drop_table('patient')
    # ### end Alembic commands ###
