"""empty message

Revision ID: a4ed8dcc35d8
Revises: aeb5a80acaf3
Create Date: 2022-01-25 10:15:12.880101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ed8dcc35d8'
down_revision = 'aeb5a80acaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('date_of_birth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'date_of_birth')
    # ### end Alembic commands ###
