"""empty message

Revision ID: aeb5a80acaf3
Revises: e0451108ddc8
Create Date: 2022-01-24 21:24:03.854518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb5a80acaf3'
down_revision = 'e0451108ddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biopsy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('tumor_normal', sa.String(), nullable=True),
    sa.Column('sample_storage_method', sa.String(), nullable=True),
    sa.Column('tumor_content', sa.Float(), nullable=True),
    sa.Column('ploidy', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('t_stage', sa.String(), nullable=True),
    sa.Column('n_stage', sa.String(), nullable=True),
    sa.Column('m_stage', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('diagnosis_detailed', sa.String(), nullable=True),
    sa.Column('dense_subtype', sa.String(), nullable=True),
    sa.Column('MSI', sa.String(), nullable=True),
    sa.Column('tumor_mutational_burden', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('biopsy_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['biopsy_id'], ['biopsy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_case',
    sa.Column('sequence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('sequence_id', 'case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_case')
    op.drop_table('sequence')
    op.drop_table('case')
    op.drop_table('biopsy')
    # ### end Alembic commands ###
